import type { CSSProperties } from 'react';

const colors = {
  page: '#f3f6fa',
  card: '#ffffff',
  border: '#d5dde8',
  text: '#16202e',
  muted: '#4a5a6e',
  primary: '#0b5cad',
  accent: '#0f7a4d',
  accentSoft: '#e6f4ec',
  errorText: '#a4161a',
  errorSoft: '#fdecec',
  tableHead: '#eaf0f7',
  selectedSoft: '#eaf2fb',
};

const card: CSSProperties = {
  background: colors.card,
  border: `1px solid ${colors.border}`,
  borderRadius: 12,
  padding: 'clamp(14px, 4vw, 24px)',
  boxShadow: '0 1px 3px rgba(22, 32, 46, 0.06)',
  minWidth: 0,
};

const headingBase: CSSProperties = {
  margin: '0 0 12px',
  color: colors.text,
};

const tableCell: CSSProperties = {
  padding: '10px 12px',
  textAlign: 'right',
  borderBottom: `1px solid ${colors.border}`,
  whiteSpace: 'nowrap',
};

export const styles: Record<string, CSSProperties> = {
  page: {
    minHeight: '100vh',
    background: colors.page,
    color: colors.text,
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    lineHeight: 1.5,
  },
  container: {
    width: '100%',
    maxWidth: 960,
    margin: '0 auto',
    padding: 'clamp(12px, 4vw, 32px)',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  header: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  title: { ...headingBase, margin: 0, fontSize: 'clamp(1.35rem, 5vw, 2rem)' },
  subtitle: { margin: '4px 0 0', color: colors.muted },
  taxYearBadge: {
    background: colors.accentSoft,
    color: colors.accent,
    fontWeight: 600,
    borderRadius: 999,
    padding: '4px 14px',
    whiteSpace: 'nowrap',
  },
  card,
  sectionHeading: { ...headingBase, fontSize: '1.15rem' },
  form: { display: 'flex', flexDirection: 'column', gap: 16 },
  fieldGroup: { display: 'flex', flexDirection: 'column', gap: 6 },
  label: { fontWeight: 600 },
  input: {
    width: '100%',
    boxSizing: 'border-box',
    padding: '12px 14px',
    fontSize: '1.1rem',
    borderRadius: 8,
    border: `1px solid ${colors.border}`,
    background: colors.card,
    color: colors.text,
  },
  inputInvalid: { border: `2px solid ${colors.errorText}` },
  errorMessage: {
    margin: 0,
    padding: '8px 12px',
    borderRadius: 8,
    background: colors.errorSoft,
    color: colors.errorText,
    fontWeight: 600,
  },
  modeFieldset: {
    border: 'none',
    padding: 0,
    margin: 0,
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
  },
  modeLegend: { fontWeight: 600, marginBottom: 6, padding: 0 },
  modeOption: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 14px',
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    cursor: 'pointer',
    background: colors.card,
  },
  modeOptionSelected: {
    border: `1px solid ${colors.primary}`,
    background: colors.selectedSoft,
  },
  resetButton: {
    alignSelf: 'flex-start',
    padding: '10px 20px',
    fontSize: '1rem',
    fontWeight: 600,
    borderRadius: 8,
    border: `1px solid ${colors.primary}`,
    background: colors.card,
    color: colors.primary,
    cursor: 'pointer',
  },
  cardGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 180px), 1fr))',
    gap: 12,
  },
  resultCard: {
    ...card,
    padding: 16,
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  resultLabel: { color: colors.muted, fontSize: '0.9rem', margin: 0 },
  resultValue: {
    margin: 0,
    fontSize: 'clamp(1.1rem, 4.5vw, 1.4rem)',
    fontWeight: 700,
    overflowWrap: 'anywhere',
  },
  rateRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 24,
    margin: '0 0 12px',
    padding: 0,
  },
  rateItem: { display: 'flex', flexDirection: 'column' },
  tableScroll: { width: '100%', overflowX: 'auto' },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: '0.95rem' },
  tableHeadCell: { ...tableCell, background: colors.tableHead, fontWeight: 600 },
  tableCell,
  tableFirstCell: { ...tableCell, textAlign: 'left' },
  tableFirstHeadCell: {
    ...tableCell,
    textAlign: 'left',
    background: colors.tableHead,
    fontWeight: 600,
  },
  disclaimer: {
    margin: 0,
    padding: '10px 14px',
    borderRadius: 8,
    background: colors.accentSoft,
    color: colors.text,
  },
  fallback: {
    ...card,
    margin: 24,
    color: colors.errorText,
    fontWeight: 600,
  },
};
